### ISSUE TITLE
Unknown function: operator#user#define error

### ISSUE THREAD

**Issue by paulhybryant** [tyru/operator-camelize.vim#2]
Plugin returned the following error

Unknown function: operator#user#define from camelize.vim line 25

**Comment by tyru** [comment]
This plugin requires operator-user.vim .
Please install it.
2015/03/08 1:51 "paulhybryant" <notifications@github.com>:

**Comment by tyru** [comment]
Please close this issue if closable.

**Comment by paulhybryant** [comment]
Thanks for the reply! Closing.
